# Generated by Django 4.2.10 on 2024-03-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conspects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(max_length=255),
        ),
    ]
